Add "only_best_status" option to Persist
yoshida-lab/XenonPy pull request #233
Opened 2021-03-07 23:40 UTC by TsumiNa

This option enables `Persist` to only save the best status of each criterion

2021-03-08 00:21 UTC, TsumiNa commented
@stewu5 Could you please check the docs for the new option? Also, the codes if you have any comment.

2021-03-08 10:22 UTC, TsumiNa commented on xenonpy/model/training/extension/persist.py
> +        only_best_states
@stewu5 Please check this line.

2021-03-08 13:01 UTC, stewu5 requested changes

2021-03-08 13:04 UTC, TsumiNa commented on xenonpy/model/training/extension/persist.py
> +        only_best_states
Thanks, updated the text.

2021-03-09 00:51 UTC, stewu5 approved these changes

2021-03-09 00:56 UTC, merged